// GENERATED by scripts/anime/registry.js (tools/anime build). Do not edit; add src/anime/world/<name>.js instead.
export const MODULE_LOADERS = {
  "_ground": () => import("./_ground.js"),
  "_houses": () => import("./_houses.js"),
  "environment": () => import("./environment.js"),
  "harbor": () => import("./harbor/index.js"),
  "life": () => import("./life/index.js"),
  "town": () => import("./town/index.js"),
  "water": () => import("./water.js"),
};
