// [v3:foundation] Writes src/anime/world/registry.js: a static map name -> () => import('./name.js') of every world
// module, so Bun can bundle them (Sakura's main.js used a template-literal dynamic import, which a bundler cannot see).
// A module is src/anime/world/<name>.js, or src/anime/world/<name>/index.js when no <name>.js exists.
// Skipped: layout.js, registry.js, and folders without index.js (helpers, layout/). Called by tools/anime/cdp.mjs build().
import { readdirSync, existsSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const WORLD = resolve(dirname(fileURLToPath(import.meta.url)), "../../src/anime/world");
const SKIP = new Set(["layout", "registry"]);

export function listModules(dir = WORLD) {
  const out = new Map();
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (f.endsWith(".js")) { const n = f.slice(0, -3); if (!SKIP.has(n)) out.set(n, `./${f}`); }
  }
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (!SKIP.has(f) && !out.has(f) && statSync(p).isDirectory() && existsSync(join(p, "index.js"))) out.set(f, `./${f}/index.js`);
  }
  return [...out.entries()].sort((a, b) => a[0].localeCompare(b[0]));
}

export function writeRegistry(dir = WORLD) {
  const mods = listModules(dir);
  const body = "// GENERATED by scripts/anime/registry.js (tools/anime build). Do not edit; add src/anime/world/<name>.js instead.\n" +
    "export const MODULE_LOADERS = {\n" + mods.map(([n, p]) => `  ${JSON.stringify(n)}: () => import(${JSON.stringify(p)}),`).join("\n") + "\n};\n";
  const file = join(dir, "registry.js");
  if (!existsSync(file) || readFileSync(file, "utf8") !== body) writeFileSync(file, body);
  return mods.map(([n]) => n);
}

if (import.meta.main) console.log(writeRegistry().join(" "));
